apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-ice-breaker
  labels:
    app: faf-ice-breaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-ice-breaker
  template:
    metadata:
      labels:
        app: faf-ice-breaker
    spec:
      containers:
        - image: faforever/faf-icebreaker:1.1.9
          name: faf-ice-breaker
          envFrom:
            - configMapRef:
                name: faf-ice-breaker
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              port: 8080
              path: /q/health
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-ice-breaker
  labels:
    app: faf-ice-breaker
data:
  ENVIRONMENT: "development"
  HYDRA_URL: "http://ory-hydra:4444"
  SELF_URL: "http://localhost:8010/ice"
  DB_USERNAME: "faf-ice-breaker"
  DB_PASSWORD: "banana"
  DB_URL: "jdbc:mariadb://faf-db:3306/faf-ice-breaker?ssl=false"
  XIRSYS_ENABLED: "false"
  XIRSYS_SECRET: "false"
  XIRSYS_IDENT: "false"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PASSWORD: "banana"
  RABBITMQ_USER: "faf-icebreaker"
  RABBITMQ_PORT: "5672"
  JWT_PRIVATE_KEY_PATH: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDXsCsl9W0vnW2k
      5GaNOVoZ6LPFYu60Y1Cd4ERRXvt8KzKTm2HHZeLKd77OLeIHR4RvJ2Q76SFwfDBM
      35F5eEx1mjPua2ljxbObsgz/bA9yBwO1RugpNOe+GoGUhPyZvmmZwqRnnQsT/SHV
      ZvRq7ej6k+KkJf09IIOxfWrGUj8SajW3iEpkuKdNpjp1dRnJdZAZ8mV1LgnwHCAf
      osL3t3+PElBSxnRQNW9iYVwB9wQAWK+aivx5warhuCeyKVtDaR0x96bOUTaKL4i/
      Uihn0CElGt5ZA907wHa6/N4Z8ssXjY+/vizYB2VYxuAG/MVkkbwWUUTGjzEEX6Ww
      h5icvVm1AgMBAAECggEAAZYYGyVc8ja0MbxETNGZKgueFtuNaeI5G5AksHyEWPtw
      WcmQxIipTFfpHVcVDHyoKrEdeZtTVaJ0MHyMc1pBJbRGoYBEvCkeEw0SL2a6Dlqi
      2lh1KKhs8+b6AP+hY/gUir71upVbGYCJGSqyrX6mcgFYb2CgJizxCwMjH+ZG9Hm0
      CkGeh4g0VDOWmx4uCChXSyoaPzD4yTJts/EOpSD61KqS+cNcnRD8PVUxwwSH+4DY
      ZSuaAUC/kFvD4qQq2lY/eia2CQi2R1Ff2TCxcbNZ34yW8IR1UBdrOPo3orQK5vSf
      iT5++MYJmTZJ8/QxY5M1nZqiyJEjTvaBQNGv8abKWQKBgQDxd/5lJkc13x8jPFJm
      EnmPvxrJaYk3MLW3dtxz1HtjHDQAvCmjXy7Ss13WhLJv9nHJDtQlSRr+l+7eNPTP
      QtiwDsqv9COfbPbvH2qcNJuNoINQ2YSKYvR0j+QlMz2dHroWEyXL4oyOfXAJ3ZrU
      lyWn/a2BD3uiJAj4p8YzJgfgnwKBgQDkqwGC6AMLPbVmhCMnUd+cxFMkYymdi8R4
      ZXMkjJiMLAOt8tkp8T0nqxC/zMfD0jnPKw1R9MP7XlM/tonLeAM/P8GUMwJnTCTc
      PvP1JxkvMG3do+7y9AbLyJsNZDkbYj1wLzvZYUrXQV/HKU4balDj3QVI6yr+W6ha
      idlsMDYBKwKBgBeuF9GdlmAvGGOhN8dwymERcbQM2HsEGN38FxR44vzOOD9WNJMj
      83iQRISUENewCGqaPK3HZJFRHwjFkrh8qrlhSflFbPTmf7TllNPqyNJzykz0d+4G
      VEjWD56iTsmIyOD/UbaT6grTPFiLVfLBO90koI5GkW5OMF8KPQKpGR6rAoGAU5NQ
      1RiZbDVcpKBs/MUG1pRG0wjPP/7Ci0KBB/2/D5RSr/QPfS3nrSTv1ToyVRbz/Az/
      LFIqgyghgyrjSBOQFEDoLpNKMJj66+iyX4qvwLiRny14eyHHjhm+2fEkkiagz+zj
      kfrmULBbIj6thoWgFPhGIzWYnCjB6n1xkwI36ssCgYACiZNHvqld4Om2IChCjIV6
      UPNLUDOvr7V1qsEy+y0dp2RQH9Es121n/v30GYfsUUYmH35CQYR0aOEqU17Qm2V7
      1auC1ZD9UeE9dy2LpW635uYf16D5FejAcmxyf/MRSBBnvFauGdS2vZ7Pf05u9Zpw
      i8UgZE7+lTYKv7+4ujmgHw==
      -----END PRIVATE KEY-----
  JWT_PUBLIC_KEY_PATH: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA17ArJfVtL51tpORmjTla
      GeizxWLutGNQneBEUV77fCsyk5thx2Xiyne+zi3iB0eEbydkO+khcHwwTN+ReXhM
      dZoz7mtpY8Wzm7IM/2wPcgcDtUboKTTnvhqBlIT8mb5pmcKkZ50LE/0h1Wb0au3o
      +pPipCX9PSCDsX1qxlI/Emo1t4hKZLinTaY6dXUZyXWQGfJldS4J8BwgH6LC97d/
      jxJQUsZ0UDVvYmFcAfcEAFivmor8ecGq4bgnsilbQ2kdMfemzlE2ii+Iv1IoZ9Ah
      JRreWQPdO8B2uvzeGfLLF42Pv74s2AdlWMbgBvzFZJG8FlFExo8xBF+lsIeYnL1Z
      tQIDAQAB
      -----END PUBLIC KEY-----

---
apiVersion: v1
kind: Service
metadata:
  name: faf-ice-breaker
  labels:
    app: faf-ice-breaker
spec:
  selector:
    app: faf-ice-breaker
  ports:
    - port: 8080
      targetPort: 8080
      
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: faf-ice-breaker-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /ice
      
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-ice-breaker-api
spec:
  entryPoints:
    - api
  routes:
    - match: Host(`localhost`) && PathPrefix(`/ice`)
      kind: Rule
      services:
        - name: faf-ice-breaker
          port: 8080
      middlewares:
        - name: faf-ice-breaker-stripprefix
        
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-ice-breaker-web
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.localhost`) && PathPrefix(`/ice`)
      kind: Rule
      services:
        - name: faf-ice-breaker
          port: 8080
      middlewares:
        - name: faf-ice-breaker-stripprefix