apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-lobby-server
  labels:
    app: faf-lobby-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-lobby-server
  template:
    metadata:
      labels:
        app: faf-lobby-server
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
        - image: faforever/faf-python-server:v1.17.0
          name: faf-lobby-server
          envFrom:
            - configMapRef:
                name: faf-lobby-server
          volumeMounts:
            - mountPath: /config/config.yaml
              name: faf-lobby-server
              subPath: "config.yaml"
          ports:
            - containerPort: 8002
          startupProbe:
            httpGet:
              port: 2000
              path: /ready
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 2000
              path: /ready
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: faf-lobby-server
          configMap:
            name: faf-lobby-server

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-lobby-server
  labels:
    app: faf-lobby-server
data:
  CONFIGURATION_FILE: "/config/config.yaml"
  "config.yaml": |
    CONFIGURATION_REFRESH_TIME: 60
    LOG_LEVEL: "TRACE"
    LISTEN:
      - ADDRESS:
        PORT: 8002
        PROTOCOL: SimpleJsonProtocol
        PROXY: false
    DB_SERVER: "faf-db"
    DB_LOGIN: "faf-python-server"
    DB_PASSWORD: "banana"
    DB_NAME: "faf"
    MQ_SERVER: "rabbitmq"
    MQ_PORT: 5672
    MQ_VHOST: "/faf-core"
    MQ_USER: "faf-python-server"
    MQ_PASSWORD: "banana"
    MQ_EXCHANGE_NAME: "faf-lobby"
    ENABLE_METRICS: false
    HYDRA_JWKS_URI: http://ory-hydra:4444/.well-known/jwks.json
    FAF_POLICY_SERVER_BASE_URL: "http://faf-policy-server:8097"
    FORCE_STEAM_LINK: "true"
    FORCE_STEAM_LINK_AFTER_DATE: 0
    USE_API: false
    PROFILING_INTERVAL: 4
    LADDER_ANTI_REPETITION_LIMIT: 2
    ALLOW_PASSWORD_LOGIN: false
    LADDER_1V1_OUTCOME_OVERRIDE: false
    MAXIMUM_RATING_IMBALANCE: 250
    MAXIMUM_RATING_DEVIATION: 250
    TIME_BONUS: 0.01
    NEWBIE_TIME_BONUS: .25
    MAXIMUM_NEWBIE_TIME_BONUS: 3.0
    MINORITY_BONUS: 1
    QUEUE_POP_TIME_MAX: 90
    USE_POLICY_SERVER: false
    
---
apiVersion: v1
kind: Service
metadata:
  name: faf-lobby-server
  labels:
    app: faf-lobby-server
spec:
  selector:
    app: faf-lobby-server
  ports:
    - port: 8002
      targetPort: 8002