apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: faf-db
  name: faf-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: faf-db
    spec:
      containers:
      - image: mariadb:12.1
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "true"
        name: mariadb
        resources: {}
        readinessProbe:
          exec:
            command: ["mariadb-admin", "ping", "-uroot", "-h127.0.0.1"]
          periodSeconds: 5
        volumeMounts:
          - name: mariadb
            mountPath: /etc/mysql/mariadb.conf.d/mysqld-custom.cnf
            subPath: mysqld-custom.cnf
      volumes:
        - name: mariadb
          configMap:
            name: mariadb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  labels:
    app: mariadb
data:
  "mysqld-custom.cnf": |-
    [mariadb]
    innodb_buffer_pool_instances = 4
    innodb_buffer_pool_size      = 16G

    #sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # Statistics
    userstat                     = 1

    plugin_load_add = query_response_time
    query_response_time_stats = on

    # ?
    event_scheduler              = on

    # Log thicc queries
    slow_query_log               = 1

    # Increase IOPS
    innodb_io_capacity = 2000
    innodb_io_capacity_max = 5000

    # Magic Mozilla configuration
    # https://github.com/letsencrypt/openzfs-nvme-databases
    #innodb_checksum_algorithm    = none
    innodb_doublewrite           = 0
    innodb_file_per_table        = on
    innodb_log_write_ahead_size  = 16384
    innodb_use_native_aio        = 0
    innodb_use_atomic_writes     = 0
    innodb_flush_neighbors       = 0

    # Enable replication features for Debezium
    log_bin                     = mysql-bin
    binlog_format               = ROW
    binlog_row_image            = FULL
    binlog_expire_logs_seconds  = 864000

---
apiVersion: batch/v1
kind: Job
metadata:
  name: faf-db-migrate
spec:
  template:
    spec:
      containers:
        - image: faforever/faf-db-migrations:v141
          name: faf-db-migrate
          args: ["migrate", "-url=jdbc:mysql://faf-db/faf?useSSL=false", "-user=root", "-password="]
          ttlSecondsAfterFinished: "0"
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: faf-db
spec:
  selector:
    app: faf-db
  ports:
  - port: 3306