apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-hydra
  labels:
    app: ory-hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-hydra
  template:
    metadata:
      labels:
        app: ory-hydra
    spec:
      containers:
        - image: oryd/hydra:v25.4.0
          name: ory-hydra
          envFrom:
            - configMapRef:
                name: ory-hydra
          ports:
            - containerPort: 4444
            - containerPort: 4445
          readinessProbe:
            httpGet:
              port: 4444
              path: /.well-known/openid-configuration
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 3
          periodSeconds: 5
          args: [ "serve", "all", "--dev"]
      restartPolicy: Always

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ory-hydra-migrate
spec:
  template:
    spec:
      containers:
        - image: oryd/hydra:v25.4.0
          name: ory-hydra
          envFrom:
            - configMapRef:
                name: ory-hydra
          args: ["migrate", "sql", "up", "--read-from-env", "--yes"]
          ttlSecondsAfterFinished: "0"
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: ory-hydra
  labels:
    app: ory-hydra
spec:
  selector:
    app: ory-hydra
  ports:
    - name: public-port
      port: 4444
      targetPort: 4444
    - name: admin-port
      port: 4445
      targetPort: 4445
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-hydra
  labels:
    app: ory-hydra
data:
  URLS_SELF_ISSUER: "http://ory-hydra:4444"
  URLS_SELF_PUBLIC: "http://localhost:4444"
  URLS_LOGIN: "http://localhost:8080/oauth2/login"
  URLS_CONSENT: "http://localhost:8080/oauth2/consent"
  STRATEGIES_ACCESS_TOKEN: "jwt"
  OAUTH2_CLIENT_CREDENTIALS_DEFAULT_GRANT_ALLOWED_SCOPE: "true"
  DSN: "postgres://hydra:banana@postgres:5432/ory-hydra"
  DB_USER: "hydra"
  DB_NAME: "ory-hydra"
  DB_PASSWOD: "banana"
  SECRETS_SYSTEM: "sfgshrtsgsdgsfgshgsg"
  
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ory-hydra
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hydra.localhost`)
      kind: Rule
      services:
        - name: ory-hydra
          port: 4444