apiVersion: v1
kind: Secret
metadata:
  name: faf-local
  namespace: kube-system
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDkzCCAnugAwIBAgIUXEdvy0PpHBm9VdYHVowO1uhu6U4wDQYJKoZIhvcNAQEL
    BQAwWTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDESMBAGA1UEAwwJbG9jYWxob3N0MB4X
    DTI1MTIwNzE4MDAyNVoXDTM1MTIwNTE4MDAyNVowWTELMAkGA1UEBhMCQVUxEzAR
    BgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5
    IEx0ZDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEA1WrymWt1S8/NW1O80aSHKKkUKrn/FbeO/RzUMELIiTgz2V3yUfKE
    bPeEQ9QjjfIK4S5fkDhUJuk18jPGx0DgV+oyTRilDSsz+bnjq+v3E/VodR75TGtx
    3IAoITrYmjRfG0w+hJ9KnKLtcSElXGEOtlxrbbylHWnh8xf7JGX7FX/wXcSmrlqc
    J5ODvHfp73/TuOOj1dUKUOjPeF9Rx0eZ5RfBq62lmOhZdwi/ZL8iaF8YLODq17lm
    3HWpmZJwoDEDcqjjBLsJ6mYg23pQs7LcCORfgz1IVpQVphYwv3vERa9Spks3GuYh
    hWqE5KSwzl6NAh9ox9mPvAeFJZiUQ7w6uwIDAQABo1MwUTAdBgNVHQ4EFgQUeo6A
    D3jJwsq7pJwrAy2QiWmX/MMwHwYDVR0jBBgwFoAUeo6AD3jJwsq7pJwrAy2QiWmX
    /MMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAOpBuhfOYlQCN
    kToAgaXVu3Ogn5rVaMSXogbZh3pUfVfw+tiEUCHd1qFQuimoRNv+D+hloqxR8S1d
    v0A1YvFDslTmcwSR21HCnEelVTDhZMLMi8ft4WNaTBYr6cq7jBsqzBKwYZeQFVPh
    Crp8rdUen4VqXIZPpvzD9cpbhn/yB0iEdNXSschlktQ+TlgNvSssc0yeWrbfMmgn
    LpZ5dmGEFihdey+7u47Cm5dbAgjxJrKNVCv1DmMkIQ5yqNPjjUk0u0wfmbTWvkTR
    +pOLITu1187KvlryipOpCm1x6KcsrsQI/n5KghaINkaCOhyTDhzweZ5vDoqBKjKx
    474Zp+AZeg==
    -----END CERTIFICATE-----
  tls.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDVavKZa3VLz81b
    U7zRpIcoqRQquf8Vt479HNQwQsiJODPZXfJR8oRs94RD1CON8grhLl+QOFQm6TXy
    M8bHQOBX6jJNGKUNKzP5ueOr6/cT9Wh1HvlMa3HcgCghOtiaNF8bTD6En0qcou1x
    ISVcYQ62XGttvKUdaeHzF/skZfsVf/BdxKauWpwnk4O8d+nvf9O446PV1QpQ6M94
    X1HHR5nlF8GrraWY6Fl3CL9kvyJoXxgs4OrXuWbcdamZknCgMQNyqOMEuwnqZiDb
    elCzstwI5F+DPUhWlBWmFjC/e8RFr1KmSzca5iGFaoTkpLDOXo0CH2jH2Y+8B4Ul
    mJRDvDq7AgMBAAECggEAHy57DPNoYI/sqdVNlzZ6EPTIijLsFC43lBUW44jpEojF
    pT1WtFEXYXG16iXKnr393PIQ6wTFNtIyxup4YTsXYYD0TH4MpM8/ztLcHY23vJDJ
    7E1+5dgk+1ng2HS9RPqLPXUhr/AzeeNMMeVCjNbEIYeAoriXSfmNwR4rMXbnp+I/
    Ie8UwFSDPUH8cHxw7TcmUktCn7KNUp8zIQZ5ykzJizaCM0+9GrcbIe+5Yd2spE9u
    n5VcaO4k3Beo36hGbNIwY4CBpUI2yJAoQKCL3m649WOjumNFPZIxhzhd9Cs+AvB3
    eQLCexRdmTDYdgrjX2X69GQH6vY98ZEm7hFTpd4WkQKBgQD0BBLSALyTUeUSnhjS
    J7A7RbKbZzDOjBncQkgJVuBTPksZvXy3sizX8kLjlgOPYy1eUnmzbfkhpfm+JFi5
    4KuiTYwOQh/czWkN9zSmySjiW0arjMPyv29rif3Sm/vXq9/h+MPR4gWCjVFI2URK
    LIVQXr2lzNAve0s/uFp5gbsELQKBgQDf5iyifCQUTSfdOUwSsTDV4oddFh21ogC4
    WhHKESgYeH4NR7PnVICRQ79V6PVl8eOrXv5A7E/PKTWdlk+ZWHdtSoSoi9H7iv0E
    LyCqo3p3ndgQKdUnTEOBapfPgAaKdZkMpel5a6t4hIlWGLna8PL29LhbryzbOQrA
    wEaYnSKDhwKBgQCq119F4HYmvqOfEUlXeaoNFZMi8nBdbAF/EHjW8RhFr8tszhnP
    ktOKrXbfWFxNu6Y774p9cXWHdWkREul72izQiXKRWQJt2PLAcF9Qlm4lbLphyUA3
    aIhdxlMLbWI5cYBh+YVAIPqymLZcRqFlPR5pUqt8tZTcaXoZtrzBbW6+UQKBgQCC
    fDBzGYolUrny0ZumISHm5Lgi5eq2mg11YviPHOSTLlW4A5uzK6op/qOZu8SYfxpC
    G4Bt8cqpXsjiaGFHaylexlj9qU7dHClMsPKGv/N1lsX+1YJl/qow2CBVS7WEJ/jk
    SCUDIF60Q/mN9acLE/VlO0XeGP85W8sKfoQmGR2uLQKBgHm+gE7jflMFc1YXoXK8
    vZo78nC8jMQVSBrIi8KYO2Tey6qpn2EBJxXG+0VLSq9plOJe3JORFRUXc0ORGSmT
    OD52FOPugIYlgNaVS/Dkts8Mw2aww4mtX51E53iGLZ8lTV+cBWujCTjznvP5sE1o
    cPRDKOo4rc/dE2dIPqrlDNav
    -----END PRIVATE KEY-----